title: "Antonis Prodromou"
description: "A minimalist portfolio powered by Minima"
url: "https://akprodromou.github.io"
baseurl: ""  # this should stay empty for user pages (not a project page)

github_username: akprodromou
linkedin_username: antonis-prodromou-1b1bb02a6

lang: en                          # site language
color_scheme: github             # syntax highlighting scheme (optional)

# Build settings
markdown: kramdown
theme: minima

exclude:
  - Gemfile
  - Gemfile.lock
  - .script
  - example

header_pages:
  - index.md
  - pages/portfolio.md
