title: "Antonis Prodromou"
description: "A minimalist portfolio powered by Kagami"
url: "https://akprodromou.github.io"
baseurl: ""

github_username: akprodromou
linkedin_username: antonis-prodromou-1b1bb02a6

baseurl: "/jekyll-theme-kagami"
lang: en # site language (en/ja/zh-Hans/zh-Hant)
color_scheme: github # this specifies color scheme for syntax highlighting

# Build settings
markdown: kramdown
theme: jekyll-theme-kagami
exclude:
  - Gemfile
  - Gemfile.lock
