title: "Antonis Prodromou"
description: "A minimalist portfolio"
url: "https://akprodromou.github.io"
baseurl: ""  

github_username: akprodromou
linkedin_username: antonis-prodromou-1b1bb02a6

lang: en                        

# Build settings
markdown: kramdown

remote_theme: pages-themes/primer@v0.6.0
plugins:
  - jekyll-remote-theme

include:
  - pages

exclude:
  - Gemfile
  - Gemfile.lock
  - .script
  - example

header_pages:
  - index.md


