title: "Antonis Prodromou"
description: "A minimalist portfolio"
url: "https://akprodromou.github.io"
baseurl: ""  

github_username: akprodromou
linkedin_username: antonis-prodromou-1b1bb02a6

lang: en                        
color_scheme: github    

# Build settings
markdown: kramdown
theme: primer

include:
  - pages

exclude:
  - Gemfile
  - Gemfile.lock
  - .script
  - example

header_pages:
  - index.md
